### ISSUE TITLE
Debugging in VSCode

### ISSUE THREAD

**Issue by AlenPelin** [josephluck/next-typescript-monorepo#5]
I am looking for some nice debugging experience in VSCode when working with NextJS via typescript in yarn workspaces-powered monorepo. I searched couple hours in the Net for good examples, but couldn't find any. 

It would be really helpful to include VSCode debugging experience in this repo.

**Comment by josephluck** [comment]
Sure thing! To be honest, I don't debug next apps in vscode so I wouldn't know the best way of modifying the repo to accommodate for that, but this project is open-source so feel free to raise a PR with anything that'll make it easier!
