### ISSUE TITLE
Deploy in production?

### ISSUE THREAD

**Issue by jemikanegara** [josephluck/next-typescript-monorepo#6]
How to take out nextjs that dependence with another packages in yarn workspace for production? Or must I copy all the workspace folders to my hosting?

**Comment by josephluck** [comment]
Hey @jemikanegara, I haven't worked on a nextjs project in quite some time, so I would imagine that this repo is pretty out of date now.

Depending on how you serve your project, you _shouldn't need_ to include all of your dependencies. for example, if you're serving your project is a next.js serverless project serving on now.sh - next and now handle all of that for you. However, if you're hosting it on a standard linux server running nodejs or something, you might need to run a build locally (using `next build`) and manually copy-paste the build output from the generated build on to your hosting provider. 

Hope this helps!

**Comment by jemikanegara** [comment]
Hi thank you for you response,

I mean I want to separate my nextjs from the yarn workspace, but it will beat the monorepo purpose, so I'll just upload the whole yarn workspace file.
